Check percentage of completion at language level

diff --git a/50-tools/po-selector b/50-tools/po-selector
--- a/50-tools/po-selector
+++ b/50-tools/po-selector
@@ -4,7 +4,7 @@
 # Only GNU gettext is supported.
 #
 # Copyright (C) 2015, SUSE Linux
-# Authors: Stanislav Brabec, Karl Eichwalder
+# Authors: Stanislav Brabec, Karl Eichwalder, Alessio Adamo
 #
 # All rights reserved.
 #
@@ -71,47 +71,59 @@ function get_po_age() {
   rm -f $1.po-date
 }
 CURRENT_date_s=$(date +%s)
+LANGS=$(echo $(ls ../*/po/*) | sed 's@ @\n@g' | awk -F '.' '{print $4}' | sort -u )
 
 cd `dirname $0`
 
-for PO in $(ls ../*/po/*.po) ; do
-  echo -n >&2 "$PO: "
-  AGE=$(get_po_age "$PO")
-  echo -n >&2 "age $AGE days "
-  if test $AGE -gt $NEW_AGE ; then
-    echo -n >&2 "(i.e. old), need ${CRITERION//_/ } $AT_LEAST% translated, "
-    THRESHOLD=$AT_LEAST
-    case $CRITERION in
-    at_least )
-      PERCENTAGE=$(get_po_percentage "$PO")
-    ;;
-    mandatory_at_least )
-      MANDATORY_POT=$(echo $PO | awk -F '.' '{gsub(".*/","",$3); print ("../50-pot/" $3 ".pot")}')
-      PERCENTAGE=$(msgmerge -N -q "$PO" $MANDATORY_POT -o - | get_po_percentage - )
-    ;;
-    esac
-  else
-    echo -n >&2 "(i.e. new), need ${CRITERION_NEW//_/ } $NEW_AT_LEAST% translated, "
-    THRESHOLD=$NEW_AT_LEAST
-    case $CRITERION_NEW in
-    at_least )
-      PERCENTAGE=$(get_po_percentage "$PO")
-    ;;
-    mandatory_at_least )
-      MANDATORY_POT=$(echo $PO | awk -F '.' '{gsub(".*/","",$3); print ("../50-pot/" $3 ".pot")}')
-      PERCENTAGE=$(msgmerge -N -q "$PO" $MANDATORY_POT -o - | get_po_percentage - )
-    ;;
-    esac
-  fi
-  if test $PERCENTAGE -ge $THRESHOLD ; then
-    echo >&2 "got $PERCENTAGE%. [passed]"
-    echo -n " $PO" | awk -F '.' '{print $4}'
-  # FIXME: Decide whether to remove this entirely, enabling this partially caused
-  # bsc#1008192
-  #elif test $(echo "$PO" | grep "^$BASELANG[-_]"); then
-  #  echo >&2 "got $PERCENTAGE%, but language is special. [passed]"
-  #  echo -n " $PO" | sed 's/\.po//'
-  else
-    echo >&2 "got $PERCENTAGE%. [failed]"
-  fi
+for LANG in $LANGS ; do
+  COUNT_TOTAL=0
+  COUNT_OK=0
+  for PO in $(ls ../$LANG/po/*.po) ; do
+    echo -n >&2 "$PO: "
+    AGE=$(get_po_age "$PO")
+    echo -n >&2 "age $AGE days "
+    if test $AGE -gt $NEW_AGE ; then
+      echo -n >&2 "(i.e. old), need ${CRITERION//_/ } $AT_LEAST% translated, "
+      THRESHOLD=$AT_LEAST
+      case $CRITERION in
+      at_least )
+        PERCENTAGE=$(get_po_percentage "$PO")
+      ;;
+      mandatory_at_least )
+        MANDATORY_POT=$(echo $PO | awk -F '.' '{gsub(".*/","",$3); print ("../50-pot/" $3 ".pot")}')
+        PERCENTAGE=$(msgmerge -N -q "$PO" $MANDATORY_POT -o - | get_po_percentage - )
+      ;;
+      esac
+    else
+      echo -n >&2 "(i.e. new), need ${CRITERION_NEW//_/ } $NEW_AT_LEAST% translated, "
+      THRESHOLD=$NEW_AT_LEAST
+      case $CRITERION_NEW in
+      at_least )
+        PERCENTAGE=$(get_po_percentage "$PO")
+      ;;
+      mandatory_at_least )
+        MANDATORY_POT=$(echo $PO | awk -F '.' '{gsub(".*/","",$3); print ("../50-pot/" $3 ".pot")}')
+        PERCENTAGE=$(msgmerge -N -q "$PO" $MANDATORY_POT -o - | get_po_percentage - )
+      ;;
+      esac
+    fi
+    if test $PERCENTAGE -ge $THRESHOLD ; then
+      echo >&2 "got $PERCENTAGE%. [passed]"
+      COUNT_OK=$((COUNT_OK+1))
+    # FIXME: Decide whether to remove this entirely, enabling this partially caused
+    # bsc#1008192
+    #elif test $(echo "$PO" | grep "^$BASELANG[-_]"); then
+    #  echo >&2 "got $PERCENTAGE%, but language is special. [passed]"
+    #  echo -n " $PO" | sed 's/\.po//'
+    else
+      echo >&2 "got $PERCENTAGE%. [failed]"
+    fi
+    COUNT_TOTAL=$((COUNT_TOTAL+1)); 
+  done
+  if test $COUNT_OK -eq $COUNT_TOTAL ; then
+      echo >&2 "Language '$LANG'... [passed]"
+      echo -n " $LANG"
+    else
+      echo >&2 "Language '$LANG'... [failed]"
+    fi
 done >../LINGUAS
