Do not create a file with source list

diff --git a/50-tools/xml-selector b/50-tools/xml-selector
--- a/50-tools/xml-selector
+++ b/50-tools/xml-selector
@@ -1,7 +1,6 @@
 #!/bin/bash
 
 # Translations selector. Returns list of languages that matches selected criterion.
-# Only GNU gettext is supported.
 #
 # Copyright (C) 2018, SUSE Linux
 # Authors: Alessio Adamo
@@ -14,15 +13,15 @@
 cd `dirname $0`
 
 if [ -z "$1" ]; then
-    echo "No argument supplied"
+    echo >&2 "No argument supplied"
     exit 1
 fi
 
 for arg in "$@"
 do
     if [ ! -f ../$arg ]; then
-        echo "File '$arg' not found!"
-        exit 1
+        echo >&2 "File '$arg' not found!"
+        exit 2
     fi
 done
 
@@ -35,5 +34,5 @@ for DC_FILE in $*; do
             echo -n "xml/$(basename $SOURCE_FILE) "
         fi
     done
-echo
-done > ../XML_SOURCES_SELECTED_DC
+echo; echo
+done
